In [12]:
import numpy as np
from sympy import Matrix
from pprint import pprint
import warnings
warnings.filterwarnings("ignore")

# Define the state matrix of |psi> in computational basis
psi = np.array([[1, 1, 1, -1]]) / 2  # Row vector for state |psi>

# Calculate the density matrix of the state |psi>
rho_psi = np.outer(psi, psi.conj())  # |psi><psi|

# Define the computational basis for subsystem B to trace out
I = np.eye(2)  # Identity matrix for 2x2, representing the basis

# Calculate the reduced density matrix for subsystem A by tracing out B
rho_A = np.zeros((2, 2))
for i in range(2):
    rho_A += np.dot(np.dot(psi[:, i*2:(i+1)*2], I), psi[:, i*2:(i+1)*2].T.conj())


# Calculate the reduced density matrix for subsystem B by tracing out A
rho_B = np.zeros((2, 2))
for i in range(2):
    rho_B += np.dot(np.dot(I, psi[:, i*2:(i+1)*2].T.conj()), psi[:, i*2:(i+1)*2])


print("rho_psi:")
display(Matrix(rho_psi))

print("rho_A:")
display(Matrix(rho_A))

print("rho_B:")
display(Matrix(rho_B))


# Calculate the eigenvalues of rho_A to determine the Schmidt coefficients
eigenvalues, _ = np.linalg.eig(rho_A)
schmidt_coefficients = np.sqrt(eigenvalues)


print("eigenvalues:")
display(Matrix(eigenvalues))
print()

print("schmidt_coefficients:")
display(Matrix(schmidt_coefficients))

print(f"rho_A:{rho_A}")
print(f"rho_B: {rho_B}")



rho_psi:


Matrix([
[ 0.25,  0.25,  0.25, -0.25],
[ 0.25,  0.25,  0.25, -0.25],
[ 0.25,  0.25,  0.25, -0.25],
[-0.25, -0.25, -0.25,  0.25]])

rho_A:


Matrix([
[1.0, 1.0],
[1.0, 1.0]])

rho_B:


Matrix([
[0.5,   0],
[  0, 0.5]])

eigenvalues:


Matrix([
[2.0],
[  0]])


schmidt_coefficients:


Matrix([
[1.4142135623731],
[              0]])

rho_A:[[1. 1.]
 [1. 1.]]
rho_B: [[0.5 0. ]
 [0.  0.5]]


In [13]:
import pandas as pd
import qutip as qt
import numpy as np


In [14]:
import qutip as qt
import numpy as np

# Basis states
q0 = qt.basis(2, 0)  # |0>
q1 = qt.basis(2, 1)  # |1>

# Constructing the composite basis states
psi00 = qt.tensor(q0, q0)  # |00>
psi01 = qt.tensor(q0, q1)  # |01>
psi10 = qt.tensor(q1, q0)  # |10>
psi11 = qt.tensor(q1, q1)  # |11>

# i. 1/2 (|00⟩ + |01⟩ + |10⟩ + |11⟩)
psi_i = (psi00 + psi01 + psi10 + psi11) / 2

# ii. 1/2 (|00⟩ + |01⟩ + |10⟩ - |11⟩)
psi_ii = (psi00 + psi01 + psi10 - psi11) / 2

# iii. 1/2 (|00⟩ + i|01⟩ + i|10⟩ - |11⟩)
psi_iii = (psi00 + 1j*psi01 + 1j*psi10 - psi11) / 2

# Normalize the states (if necessary)
psi_i = psi_i.unit()
psi_ii = psi_ii.unit()
psi_iii = psi_iii.unit()

# Output the states
print("State i:\n", psi_i)
print("State ii:\n", psi_ii)
print("State iii:\n", psi_iii)


# Density matrices
rho_i = psi_i * psi_i.dag()
rho_ii = psi_ii * psi_ii.dag()
rho_iii = psi_iii * psi_iii.dag()

print("Density Matrix of psi_i:\n", rho_i)
print("Density Matrix of psi_ii:\n", rho_ii)
print("Density Matrix of psi_iii:\n", rho_iii)

# Performing partial trace on rho_i to trace out subsystem B
rdm_A_i = qt.ptrace(rho_i, 0)  # Keeping only subsystem A
rdm_B_i = qt.ptrace(rho_i, 1)  # Keeping only subsystem B
rdm_A_ii = qt.ptrace(rho_ii, 0)  # Keeping only subsystem A
rdm_B_ii = qt.ptrace(rho_ii, 1)  # Keeping only subsystem B
rdm_A_iii = qt.ptrace(rho_iii,0)  # Keeping only subsystem B
rdm_B_iii = qt.ptrace(rho_iii, 1)  # Keeping only subsystem B

print("Reduced Density Matrix of Subsystem A for psi_i:\n", rdm_A_i)
# print("Reduced Density Matrix of Subsystem B for psi_i:\n", rdm_B_i)
# Performing partial trace on rho_i to trace out subsystem B

print("Reduced Density Matrix of Subsystem A for psi_ii:\n", rdm_A_ii)
# print("Reduced Density Matrix of Subsystem B for psi_ii:\n", rdm_B_ii)

# Von Neumann Entropy
S_vN = qt.entropy_vn(rdm_A_iii, base=2)
print("Von Neumann Entropy:", S_vN)

# Negativity
negativity = qt.negativity(rdm_A_iii, [0, 1],)
print("Negativity:", negativity)


concurrence = qt.concurrence(rho_iii)
print("Concurrence:", concurrence)


State i:
 Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
State ii:
 Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.5]
 [ 0.5]
 [ 0.5]
 [-0.5]]
State iii:
 Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.5+0.j ]
 [ 0. +0.5j]
 [ 0. +0.5j]
 [-0.5+0.j ]]
Density Matrix of psi_i:
 Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]]
Density Matrix of psi_ii:
 Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.25  0.25  0.25 -0.25]
 [ 0.25  0.25  0.25 -0.25]
 [ 0.25  0.25  0.25 -0.25]
 [-0.25 -0.25 -0.25  0.25]]
Density Matrix of psi_iii:
 Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.25+0.j    0.  -0.25j  0.  -0.25j -0.

In [15]:
from IPython.display import display
from sympy import Matrix, pprint
from qiskit.quantum_info import Statevector

def calculate_metrics(psi):

    statevector = Statevector(psi.data.toarray())
    display(statevector.draw('latex'))
    display(psi)

    # Calculate density matrix
    rho = psi * psi.dag()

    # Print density matrix
    print("Density Matrix of psi:\n")
    display(Matrix(rho.full()))

    # Perform partial trace to trace out subsystems
    rdm_A = qt.ptrace(rho, 0)  # Keep only subsystem A
    rdm_B = qt.ptrace(rho, 1)  # Keep only subsystem B

    # Print reduced density matrices
    print("Reduced Density Matrix of Subsystem A for psi:\n")
    display(Matrix(rdm_A.full()))

    print("Reduced Density Matrix of Subsystem B for psi:\n")
    display(Matrix(rdm_B.full()))


    # Calculate the eigenvalues
    eigenvalues, _ = np.linalg.eig(rdm_A)
    schmidt_coefficients = np.sqrt(eigenvalues)

    # Print eigenvalues and Schmidt coefficients
    print(f"Eigenvalues: {eigenvalues}, Schmidt Coefficients: {schmidt_coefficients}")

    # Calculate Von Neumann Entropy
    S_vN = qt.entropy_vn(rdm_A, base=2)

    # Calculate Negativity
    negativity = qt.negativity(rdm_A, [0, 1])

    # Calculate Concurrence
    concurrence = qt.concurrence(rho)


    # Print metrics
    print(f"Von Neumann Entropy: {S_vN:.4f}")
    print(f"Negativity: {format(negativity, '.2e')}")
    print(f"Concurrence: {concurrence:.4f}")

    # Return metrics in a dictionary
    return {
        "rho": rho,
        'rdm_A': rdm_A,
        'rdm_B': rdm_B,
        "Von Neumann Entropy": S_vN,
            "Negativity": negativity,
            "Concurrence": concurrence
            }

metrics = calculate_metrics(psi_i)
# print(metrics)

<IPython.core.display.Latex object>

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.5]
 [0.5]
 [0.5]
 [0.5]]

Density Matrix of psi:



Matrix([
[0.25, 0.25, 0.25, 0.25],
[0.25, 0.25, 0.25, 0.25],
[0.25, 0.25, 0.25, 0.25],
[0.25, 0.25, 0.25, 0.25]])

Reduced Density Matrix of Subsystem A for psi:



Matrix([
[0.5, 0.5],
[0.5, 0.5]])

Reduced Density Matrix of Subsystem B for psi:



Matrix([
[0.5, 0.5],
[0.5, 0.5]])

Eigenvalues: [1.0000000e+00+0.j 7.2203753e-33+0.j], Schmidt Coefficients: [1.00000000e+00+0.j 8.49727916e-17+0.j]
Von Neumann Entropy: -0.0000
Negativity: -1.11e-16
Concurrence: 0.0000


In [16]:
print(metrics.keys())
metrics = calculate_metrics(psi_i)

rdm_A = metrics['rdm_A']

eigenvalues, _ = np.linalg.eig(rdm_A)
sorted_eigenvalues = np.negative(eigenvalues) # Sort eigenvalues in decreasing order

schmidt_coefficients = (sorted_eigenvalues)
display(Matrix(sorted_eigenvalues))

# Calc negativity

print(sorted_eigenvalues)
eigen_sum = (sorted_eigenvalues).sum()
print(f"Eigen Sum: {eigen_sum.astype(float)}")
# negativity = np.maximum(0, 2 * eigen_sum)
negativity = eigen_sum
print(f"Negativity Custom: {format(negativity.astype(float))}, Negativity QuTiP: {metrics['Negativity']}")

dict_keys(['rho', 'rdm_A', 'rdm_B', 'Von Neumann Entropy', 'Negativity', 'Concurrence'])


<IPython.core.display.Latex object>

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.5]
 [0.5]
 [0.5]
 [0.5]]

Density Matrix of psi:



Matrix([
[0.25, 0.25, 0.25, 0.25],
[0.25, 0.25, 0.25, 0.25],
[0.25, 0.25, 0.25, 0.25],
[0.25, 0.25, 0.25, 0.25]])

Reduced Density Matrix of Subsystem A for psi:



Matrix([
[0.5, 0.5],
[0.5, 0.5]])

Reduced Density Matrix of Subsystem B for psi:



Matrix([
[0.5, 0.5],
[0.5, 0.5]])

Eigenvalues: [1.0000000e+00+0.j 7.2203753e-33+0.j], Schmidt Coefficients: [1.00000000e+00+0.j 8.49727916e-17+0.j]
Von Neumann Entropy: -0.0000
Negativity: -1.11e-16
Concurrence: 0.0000


Matrix([
[                 -1.0],
[-7.22037530394613e-33]])

[-1.0000000e+00-0.j -7.2203753e-33-0.j]
Eigen Sum: -1.0
Negativity Custom: -1.0, Negativity QuTiP: -1.1102230246251565e-16


In [17]:
eigen_diff = [sorted_eigenvalues[i] - sorted_eigenvalues[i+1] for i in range(len(sorted_eigenvalues)-1)]

In [18]:
%connect_info

{"key":"f9d41c6f-2a24-4f18-8283-bf1129a48759","signature_scheme":"hmac-sha256","transport":"tcp","ip":"127.0.0.1","hb_port":9005,"control_port":9006,"shell_port":9007,"stdin_port":9013,"iopub_port":9014,"kernel_name":"pythonjvsc74a57bd0ed8d7b49b05be800232621fba4e36505cdb7e1d202d0289295f6e35d59c3092a"}

Paste the above JSON into a file, and connect with:
    $> jupyter <app> --existing <file>
or, if you are local, you can connect with just:
    $> jupyter <app> --existing kernel-v2-45158J4Khd2CpxGUu.json
or even just:
    $> jupyter <app> --existing
if this is the most recent Jupyter kernel you have started.


In [21]:
metrics = calculate_metrics(psi_i)

<IPython.core.display.Latex object>

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.5]
 [0.5]
 [0.5]
 [0.5]]

Density Matrix of psi:



Matrix([
[0.25, 0.25, 0.25, 0.25],
[0.25, 0.25, 0.25, 0.25],
[0.25, 0.25, 0.25, 0.25],
[0.25, 0.25, 0.25, 0.25]])

Reduced Density Matrix of Subsystem A for psi:



Matrix([
[0.5, 0.5],
[0.5, 0.5]])

Reduced Density Matrix of Subsystem B for psi:



Matrix([
[0.5, 0.5],
[0.5, 0.5]])

Eigenvalues: [1.0000000e+00+0.j 7.2203753e-33+0.j], Schmidt Coefficients: [1.00000000e+00+0.j 8.49727916e-17+0.j]
Von Neumann Entropy: -0.0000
Negativity: -1.11e-16
Concurrence: 0.0000


In [19]:
metrics = calculate_metrics(psi_ii)

<IPython.core.display.Latex object>

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.5]
 [ 0.5]
 [ 0.5]
 [-0.5]]

Density Matrix of psi:



Matrix([
[ 0.25,  0.25,  0.25, -0.25],
[ 0.25,  0.25,  0.25, -0.25],
[ 0.25,  0.25,  0.25, -0.25],
[-0.25, -0.25, -0.25,  0.25]])

Reduced Density Matrix of Subsystem A for psi:



Matrix([
[0.5,   0],
[  0, 0.5]])

Reduced Density Matrix of Subsystem B for psi:



Matrix([
[0.5,   0],
[  0, 0.5]])

Eigenvalues: [0.5+0.j 0.5+0.j], Schmidt Coefficients: [0.70710678+0.j 0.70710678+0.j]
Von Neumann Entropy: 1.0000
Negativity: 0.00e+00
Concurrence: 1.0000


### Psi iii

In [20]:
metrics = calculate_metrics(psi_iii)

<IPython.core.display.Latex object>

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.5+0.j ]
 [ 0. +0.5j]
 [ 0. +0.5j]
 [-0.5+0.j ]]

Density Matrix of psi:



Matrix([
[  0.25, -0.25*I, -0.25*I,   -0.25],
[0.25*I,    0.25,    0.25, -0.25*I],
[0.25*I,    0.25,    0.25, -0.25*I],
[ -0.25,  0.25*I,  0.25*I,    0.25]])

Reduced Density Matrix of Subsystem A for psi:



Matrix([
[  0.5, -0.5*I],
[0.5*I,    0.5]])

Reduced Density Matrix of Subsystem B for psi:



Matrix([
[  0.5, -0.5*I],
[0.5*I,    0.5]])

Eigenvalues: [1.0000000e+00+0.j 7.2203753e-33+0.j], Schmidt Coefficients: [1.00000000e+00+0.j 8.49727916e-17+0.j]
Von Neumann Entropy: -0.0000
Negativity: -1.11e-16
Concurrence: 0.0000


In [23]:
psi = psi_iii
print(psi)

statevector = Statevector(psi.data.toarray())
display(statevector.draw('latex'))
display(psi)

# Calculate density matrix
rho = psi * psi.dag()

# Print density matrix
print("Density Matrix of psi:\n")
display(Matrix(rho.full()))

# Perform partial trace to trace out subsystems
rdm_A = qt.ptrace(rho, 0)  # Keep only subsystem A
rdm_B = qt.ptrace(rho, 1)  # Keep only subsystem B

# Print reduced density matrices
print("Reduced Density Matrix of Subsystem A for psi:\n")
display(Matrix(rdm_A.full()))

print("Reduced Density Matrix of Subsystem B for psi:\n")
display(Matrix(rdm_B.full()))


# Calculate the eigenvalues
eigenvalues, _ = np.linalg.eig(rdm_A)
schmidt_coefficients = np.sqrt(eigenvalues)

# Print eigenvalues and Schmidt coefficients
print(f"Eigenvalues: {eigenvalues}, Schmidt Coefficients: {schmidt_coefficients}")

# Calculate Von Neumann Entropy
S_vN = qt.entropy_vn(rdm_A, base=2)

# Calculate Negativity
negativity = qt.negativity(rdm_A, [0, 1])

# Calculate Concurrence
concurrence = qt.concurrence(rho)

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.5+0.j ]
 [ 0. +0.5j]
 [ 0. +0.5j]
 [-0.5+0.j ]]


<IPython.core.display.Latex object>

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.5+0.j ]
 [ 0. +0.5j]
 [ 0. +0.5j]
 [-0.5+0.j ]]

Density Matrix of psi:



Matrix([
[  0.25, -0.25*I, -0.25*I,   -0.25],
[0.25*I,    0.25,    0.25, -0.25*I],
[0.25*I,    0.25,    0.25, -0.25*I],
[ -0.25,  0.25*I,  0.25*I,    0.25]])

Reduced Density Matrix of Subsystem A for psi:



Matrix([
[  0.5, -0.5*I],
[0.5*I,    0.5]])

Reduced Density Matrix of Subsystem B for psi:



Matrix([
[  0.5, -0.5*I],
[0.5*I,    0.5]])

Eigenvalues: [1.0000000e+00+0.j 7.2203753e-33+0.j], Schmidt Coefficients: [1.00000000e+00+0.j 8.49727916e-17+0.j]


$$|ψ⟩AB = 1/√3 (|00⟩ + |01⟩ + |10⟩)$$

In [35]:
# Basis states
q0 = qt.basis(2, 0)  # |0>
q1 = qt.basis(2, 1)  # |1>

# Constructing the composite basis states
psi00 = qt.tensor(q0, q0)  # |00>
psi01 = qt.tensor(q0, q1)  # |01>
psi10 = qt.tensor(q1, q0)  # |10>
psi11 = qt.tensor(q1, q1)  # |11>

# $|ψ⟩AB = 1/√3 (|00⟩ + |01⟩ + |10⟩)$

psi = (psi00 + psi01 + psi10) / np.sqrt(3)

display(psi)

statevector = Statevector(psi.data.toarray())
display(statevector.draw('latex'))



# calc
metrics = calculate_metrics(psi)
rho, rdm_A, rdm_B = metrics['rho'], metrics['rdm_A'], metrics['rdm_B']

print('-'*100)

# Calculate the eigenvalues
eigenvalues, _ = np.linalg.eig(rdm_A)
schmidt_coefficients = np.sqrt(eigenvalues)
print('schmidt and eigenvalues A')
display(Matrix(schmidt_coefficients))
display(Matrix(eigenvalues))

eigenvalues, _ = np.linalg.eig(rdm_B)
schmidt_coefficients = np.sqrt(eigenvalues)
print('schmidt and eigenvalues B')
display(Matrix(schmidt_coefficients))
display(Matrix(eigenvalues))


Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.57735027]
 [0.57735027]
 [0.57735027]
 [0.        ]]

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.57735027]
 [0.57735027]
 [0.57735027]
 [0.        ]]

Density Matrix of psi:



Matrix([
[0.333333333333333, 0.333333333333333, 0.333333333333333, 0],
[0.333333333333333, 0.333333333333333, 0.333333333333333, 0],
[0.333333333333333, 0.333333333333333, 0.333333333333333, 0],
[                0,                 0,                 0, 0]])

Reduced Density Matrix of Subsystem A for psi:



Matrix([
[0.666666666666667, 0.333333333333333],
[0.333333333333333, 0.333333333333333]])

Reduced Density Matrix of Subsystem B for psi:



Matrix([
[0.666666666666667, 0.333333333333333],
[0.333333333333333, 0.333333333333333]])

Eigenvalues: [0.872678+0.j 0.127322+0.j], Schmidt Coefficients: [0.93417236+0.j 0.35682209+0.j]
Von Neumann Entropy: 0.5500
Negativity: 1.11e-16
Concurrence: 0.6667
----------------------------------------------------------------------------------------------------
schmidt and eigenvalues A


Matrix([
[0.934172358962716],
[ 0.35682208977309]])

Matrix([
[0.872677996249965],
[0.127322003750035]])

schmidt and eigenvalues B


Matrix([
[0.934172358962716],
[ 0.35682208977309]])

Matrix([
[0.872677996249965],
[0.127322003750035]])

In [39]:
e0 = (3 + np.sqrt(5))/6
e1 = (3 - np.sqrt(5))/6

pho_a = e0**2 + e1**2
pho_a

0.7777777777777779

In [41]:
coe1 = 1/(np.sqrt((5 + np.sqrt(5))/2))
coe2 = 1/(np.sqrt((5 - np.sqrt(5))/2))

v1 = np.array([1+np.sqrt(5)/2, 1])
v2 = np.array([1-np.sqrt(5)/2, 1])

coe1 *v1

array([1.11351636, 0.52573111])

In [44]:
v1, v2, coe1, coe2

(array([2.11803399, 1.        ]),
 array([-0.11803399,  1.        ]),
 0.5257311121191336,
 0.8506508083520399)